#!/bin/bash

set -e; set -u; set -o pipefail

[[ ! ${1-} ]] && echo "Missing query file" && exit 1

curl -H "Content-Type:application/sparql-query" -H "Accept:text/csv" --data-binary "@$1" -X POST http://localhost:8080/sparql
